version: "3.8"

services:
  web:
    depends_on: 
      - api
    build: ./client
    ports:
      - 5173:5173
    env_file:
      - web.env
    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
        - path: ./client
          target: /app
          action: sync

  api: 
    depends_on: 
      - db
    build: ./server
    ports: 
      - 3000:3000
    env_file:
      - api.env
    develop:
      watch:
        - path: ./server/package.json
          action: rebuild
        - path: ./server/package-lock.json
          action: rebuild
        - path: ./server
          target: /app
          action: sync

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - moz-services:/data/db

volumes:
  moz-services: